# Generated by Django 3.2.6 on 2021-08-07 01:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
